name: Update

on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: update
        run: |
          cd ${{github.workspace}}

          git config --global user.name 'redex2.dev'
          git config --global user.email 'postmaster@redex2.dev'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          
          chmod +x .github/update.sh
          ./.github/update.sh

      
